### PR TITLE
fix errors mentioned in issue #2

### PR DESCRIPTION
**Pull request by vaibhavhrt**

### CODE REVIEW

**Comment by vaibhavhrt** [comment]
fix issue #2

**Comment by srinivasgadi77** [comment]
I composed the whole scenario in Django-users, could you have a look.
, below is the which take you to there.

https://groups.google.com/forum/#!searchin/django-users/Error$20at$20OneToOneField$20in$20models$20while$20creating$20new$20models$20class%7Csort:date/django-users/YtS1mpHDyss/8vKJcQeUGQAJ

**Comment by srinivasgadi77** [comment]
here is the complete content of the issue.

I am facing below error while creating a new model class.
the error pops up only at this line "user = models.OneToOneField(User)"
"E1120:No value for argument 'on_delete' in constructor call"

**section/models.py**

```
from django.db import models
from django.contrib.auth.models import User

class userProfile(models.Model):
    user = models.OneToOneField(User)

```
**admin.py**

```
from django.contrib import admin
from section.models import userProfile

admin.site.register(userProfile)

```
If I add below entry with "on_delete=models.CASCADE"

`user = models.OneToOneField(User,on_delete=models.CASCADE)`
the error got subsided but the new class "userProfile" is not appearing in admin page, under Users tab.

Also, run migrations:

```
C:\Users\srini\djangoProjects\college>python manage.py makemigrations
No changes detected

```
```
C:\Users\srini\djangoProjects\college>python manage.py migrate
Operations to perform:
Apply all migrations: admin, auth, contenttypes, sessions
Running migrations:
No migrations to apply.

```
Followed the below troubleshooting steps, but no vain.
1. Deleted the migrations folder
2. Removed the SQLite3 DB itself
3. My dir structure.
```
24-09-2018  16:37    <DIR>          .
24-09-2018  16:37    <DIR>          ..
23-09-2018  15:06    <DIR>          college
19-09-2018  08:56               554 manage.py
19-09-2018  10:59    <DIR>          section
               1 File(s)            554 bytes
               4 Dir(s)  32,464,281,600 bytes free

```
4. Execute the makemigrations, but it prompting with the error. 
```
C:\Users\srini\djangoProjects\college>python manage.py makemigrations section
App 'section' could not be found. Is it in INSTALLED_APPS?

```
5. FYI: Also registered in **apps.py**
```
from django.apps import AppConfig

class ClassConfig(AppConfig):
name = 'section'
```

**Comment by vaibhavhrt** [comment]
Merge this pull request, I will start working, I have fixed everything. Look at Files Changed tab on top to see what changes I made.

**Comment by vaibhavhrt** [comment]
To be more specific look at changes in just forms.py and settings.py. Other changes are not important. I have changed just a couple of lines in those files.

**Review by srinivasgadi77 — APPROVED** [review]

**Review by srinivasgadi77 — APPROVED** [review]

**Comment by srinivasgadi77** [comment]
Thank you very much Bro, some how I managed to fix the forms.py issue, but you made my day fixing the settings.py.
Hope I can ask few more question further If arise any :)

**Comment by vaibhavhrt** [comment]
yeah sure.

**Pull request closed without merging**
